# Base environment variables
x-base-env: &base-env
  # ClickHouse connection settings
  CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
  CLICKHOUSE_PORT: ${CLICKHOUSE_PORT:-443}
  CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
  CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
  CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE:-beacon_chain}
  LOG_LEVEL: ${LOG_LEVEL:-20}
  
  # Migration settings
  CH_MIGRATIONS_DIR: /app/migrations
  CH_SECURE: "True"
  CH_VERIFY: "False"

# Complete environment for scrapers (includes base env)
x-complete-env: &complete-env
  # ClickHouse settings
  CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
  CLICKHOUSE_PORT: ${CLICKHOUSE_PORT:-443}
  CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
  CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
  CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE:-beacon_chain}
  
  # Migration settings
  CH_MIGRATIONS_DIR: /app/migrations
  CH_SECURE: "True"
  CH_VERIFY: "False"
  
  # Beacon chain settings
  BEACON_NODE_URL: ${BEACON_NODE_URL}
  
  # Scraper mode and configuration
  SCRAPER_MODE: ${SCRAPER_MODE:-realtime}
  ENABLED_SCRAPERS: ${ENABLED_SCRAPERS:-block,validator,reward,blob,specs}
  
  # Historical mode settings
  HISTORICAL_START_SLOT: ${HISTORICAL_START_SLOT:-0}
  HISTORICAL_END_SLOT: ${HISTORICAL_END_SLOT:-}
  
  # Batch and concurrency settings
  BATCH_SIZE: ${BATCH_SIZE:-100}
  MAX_CONCURRENT_REQUESTS: ${MAX_CONCURRENT_REQUESTS:-5}
  
  # Parallel mode settings
  PARALLEL_WORKERS: ${PARALLEL_WORKERS:-4}
  
  # General settings
  LOG_LEVEL: ${LOG_LEVEL:-20}

services:
  # Migration service to run separately if needed
  beacon-migrate:
    image: beacon-indexer:latest
    container_name: beacon-migrate
    environment:
      <<: *base-env
      CH_DIRECTION: ${CH_DIRECTION:-up}
    volumes:
      - ./migrations:/app/migrations
      - ./scripts/run_clickhouse_migrations.py:/app/scripts/run_clickhouse_migrations.py
    command: python /app/scripts/run_clickhouse_migrations.py

  specs-updater:
    image: beacon-indexer:latest
    container_name: beacon-specs-updater
    environment:
      <<: *complete-env
    volumes:
      - ./migrations:/app/migrations
      - ./scripts/update_specs.py:/app/scripts/update_specs.py
    command: >
      python -m scripts.update_specs
    networks:
      - beacon-network
    profiles:
      - specs

  # Main unified scraper service
  beacon-scraper:
    image: beacon-indexer:latest
    container_name: beacon-scraper
    environment:
      <<: *complete-env
    volumes:
      - ./migrations:/app/migrations
      - ./scripts/run_clickhouse_migrations.py:/app/scripts/run_clickhouse_migrations.py
    command: python -m src.main
    restart: unless-stopped
    networks:
      - beacon-network

networks:
  beacon-network: