services:
  # Migration service - Set up database schema
  migration:
    image: beacon-indexer:latest
    container_name: migration
    environment:
      - STORAGE_BACKEND=${STORAGE_BACKEND}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE}
      - PARQUET_OUTPUT_DIR=${PARQUET_OUTPUT_DIR}
      - PARQUET_COMPRESSION=${PARQUET_COMPRESSION}
      - PARQUET_ROWS_PER_FILE=${PARQUET_ROWS_PER_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./parquet_data:/app/parquet_data
    command: ["python", "scripts/migrate.py"]
    profiles:
      - migration

  # Backfill service - Load historical raw data
  backfill:
    image: beacon-indexer:latest
    container_name: backfill
    environment:
      - BEACON_NODE_URL=${BEACON_NODE_URL}
      - STORAGE_BACKEND=${STORAGE_BACKEND}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE}
      - PARQUET_OUTPUT_DIR=${PARQUET_OUTPUT_DIR}
      - PARQUET_COMPRESSION=${PARQUET_COMPRESSION}
      - PARQUET_ROWS_PER_FILE=${PARQUET_ROWS_PER_FILE}
      - ENABLED_LOADERS=${ENABLED_LOADERS}
      - VALIDATOR_MODE=${VALIDATOR_MODE}
      - START_SLOT=${START_SLOT}
      - END_SLOT=${END_SLOT}
      - BACKFILL_WORKERS=${BACKFILL_WORKERS}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./parquet_data:/app/parquet_data
    command: ["python", "-m", "src.main", "load", "backfill"]
    profiles:
      - backfill

  # Realtime service - Load new raw data continuously
  realtime:
    image: beacon-indexer:latest
    container_name: realtime
    environment:
      - BEACON_NODE_URL=${BEACON_NODE_URL}
      - STORAGE_BACKEND=${STORAGE_BACKEND}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE}
      - PARQUET_OUTPUT_DIR=${PARQUET_OUTPUT_DIR}
      - PARQUET_COMPRESSION=${PARQUET_COMPRESSION}
      - PARQUET_ROWS_PER_FILE=${PARQUET_ROWS_PER_FILE}
      - ENABLED_LOADERS=${ENABLED_LOADERS}
      - VALIDATOR_MODE=${VALIDATOR_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./parquet_data:/app/parquet_data
    command: ["python", "-m", "src.main", "load", "realtime"]
    restart: unless-stopped
    profiles:
      - realtime

  # Transform service - Process raw data into structured tables (BATCH MODE - exits when done)
  transform:
    image: beacon-indexer:latest
    container_name: transform
    environment:
      - STORAGE_BACKEND=${STORAGE_BACKEND}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE}
      - PARQUET_OUTPUT_DIR=${PARQUET_OUTPUT_DIR}
      - PARQUET_COMPRESSION=${PARQUET_COMPRESSION}
      - PARQUET_ROWS_PER_FILE=${PARQUET_ROWS_PER_FILE}
      - ENABLED_LOADERS=${ENABLED_LOADERS}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./parquet_data:/app/parquet_data
    command: ["python", "-m", "src.main", "transform", "batch"]
    profiles:
      - transform

  # Transform continuous service - Process raw data continuously (stays running)
  transform-continuous:
    image: beacon-indexer:latest
    container_name: transform-continuous
    environment:
      - STORAGE_BACKEND=${STORAGE_BACKEND}
      - CLICKHOUSE_HOST=${CLICKHOUSE_HOST}
      - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_SECURE=${CLICKHOUSE_SECURE}
      - PARQUET_OUTPUT_DIR=${PARQUET_OUTPUT_DIR}
      - PARQUET_COMPRESSION=${PARQUET_COMPRESSION}
      - PARQUET_ROWS_PER_FILE=${PARQUET_ROWS_PER_FILE}
      - ENABLED_LOADERS=${ENABLED_LOADERS}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./parquet_data:/app/parquet_data
    command: ["python", "-m", "src.main", "transform", "run", "--continuous"]
    restart: unless-stopped
    profiles:
      - transform-continuous